variable "name" {}
variable "location" {}
variable "resource_group_name" {}
variable "dns_prefix" {}
variable "node_count" {}
variable "vm_size" {}
variable "subnet_id" {}
variable "pod_cidr" {}
variable "service_cidr" {}
variable "dns_service_ip" {}