apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-crud-test

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
        version: v1

    spec:
      containers:
      - name: backend
        image: chefallacr.azurecr.io/aks-crud-backend:latest

        ports:
        - containerPort: 3000

        env:
        - name: DB_HOST
          value: postgres

        - name: DB_PORT
          value: "5432"

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: employee-crud-test

spec:
  selector:
    app: backend

  ports:
    - port: 80
      targetPort: 3000