apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: employee-crud-test
type: Opaque
stringData:
  POSTGRES_DB: employeesdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres