apiVersion: v1
kind: ResourceQuota
metadata:
  name: employee-crud-quota
  namespace: employee-crud-test
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "30"
    limits.memory: 20Gi
    pods: "30"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: employee-crud-limits
  namespace: employee-crud-test
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
