name: Build Scan Push Update GitOps

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: aks-devsecops-app

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Docker build
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_NAME:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true